//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace EF.Model.DataContext
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class bbHomeEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“bbHomeEntities”部分中的连接字符串初始化新 bbHomeEntities 对象。
        /// </summary>
        public bbHomeEntities() : base("name=bbHomeEntities", "bbHomeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 bbHomeEntities 对象。
        /// </summary>
        public bbHomeEntities(string connectionString) : base(connectionString, "bbHomeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 bbHomeEntities 对象。
        /// </summary>
        public bbHomeEntities(EntityConnection connection) : base(connection, "bbHomeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<base_t_membAddr> base_t_membAddr
        {
            get
            {
                if ((_base_t_membAddr == null))
                {
                    _base_t_membAddr = base.CreateObjectSet<base_t_membAddr>("base_t_membAddr");
                }
                return _base_t_membAddr;
            }
        }
        private ObjectSet<base_t_membAddr> _base_t_membAddr;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<base_t_member> base_t_member
        {
            get
            {
                if ((_base_t_member == null))
                {
                    _base_t_member = base.CreateObjectSet<base_t_member>("base_t_member");
                }
                return _base_t_member;
            }
        }
        private ObjectSet<base_t_member> _base_t_member;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tb_Blacklist> tb_Blacklist
        {
            get
            {
                if ((_tb_Blacklist == null))
                {
                    _tb_Blacklist = base.CreateObjectSet<tb_Blacklist>("tb_Blacklist");
                }
                return _tb_Blacklist;
            }
        }
        private ObjectSet<tb_Blacklist> _tb_Blacklist;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<system_log> system_log
        {
            get
            {
                if ((_system_log == null))
                {
                    _system_log = base.CreateObjectSet<system_log>("system_log");
                }
                return _system_log;
            }
        }
        private ObjectSet<system_log> _system_log;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<System_Permission> System_Permission
        {
            get
            {
                if ((_System_Permission == null))
                {
                    _System_Permission = base.CreateObjectSet<System_Permission>("System_Permission");
                }
                return _System_Permission;
            }
        }
        private ObjectSet<System_Permission> _System_Permission;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 base_t_membAddr EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTobase_t_membAddr(base_t_membAddr base_t_membAddr)
        {
            base.AddObject("base_t_membAddr", base_t_membAddr);
        }
    
        /// <summary>
        /// 用于向 base_t_member EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTobase_t_member(base_t_member base_t_member)
        {
            base.AddObject("base_t_member", base_t_member);
        }
    
        /// <summary>
        /// 用于向 tb_Blacklist EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotb_Blacklist(tb_Blacklist tb_Blacklist)
        {
            base.AddObject("tb_Blacklist", tb_Blacklist);
        }
    
        /// <summary>
        /// 用于向 system_log EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTosystem_log(system_log system_log)
        {
            base.AddObject("system_log", system_log);
        }
    
        /// <summary>
        /// 用于向 System_Permission EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSystem_Permission(System_Permission system_Permission)
        {
            base.AddObject("System_Permission", system_Permission);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EF.Model.bbHomeModel", Name="base_t_membAddr")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class base_t_membAddr : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 base_t_membAddr 对象。
        /// </summary>
        /// <param name="addressNo">addressNo 属性的初始值。</param>
        /// <param name="membNo">membNo 属性的初始值。</param>
        /// <param name="createTime">createTime 属性的初始值。</param>
        /// <param name="createBy">createBy 属性的初始值。</param>
        public static base_t_membAddr Createbase_t_membAddr(global::System.Int32 addressNo, global::System.Int32 membNo, global::System.DateTime createTime, global::System.String createBy)
        {
            base_t_membAddr base_t_membAddr = new base_t_membAddr();
            base_t_membAddr.addressNo = addressNo;
            base_t_membAddr.membNo = membNo;
            base_t_membAddr.createTime = createTime;
            base_t_membAddr.createBy = createBy;
            return base_t_membAddr;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 addressNo
        {
            get
            {
                return _addressNo;
            }
            set
            {
                if (_addressNo != value)
                {
                    OnaddressNoChanging(value);
                    ReportPropertyChanging("addressNo");
                    _addressNo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("addressNo");
                    OnaddressNoChanged();
                }
            }
        }
        private global::System.Int32 _addressNo;
        partial void OnaddressNoChanging(global::System.Int32 value);
        partial void OnaddressNoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 membNo
        {
            get
            {
                return _membNo;
            }
            set
            {
                OnmembNoChanging(value);
                ReportPropertyChanging("membNo");
                _membNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("membNo");
                OnmembNoChanged();
            }
        }
        private global::System.Int32 _membNo;
        partial void OnmembNoChanging(global::System.Int32 value);
        partial void OnmembNoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String roadName
        {
            get
            {
                return _roadName;
            }
            set
            {
                OnroadNameChanging(value);
                ReportPropertyChanging("roadName");
                _roadName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("roadName");
                OnroadNameChanged();
            }
        }
        private global::System.String _roadName;
        partial void OnroadNameChanging(global::System.String value);
        partial void OnroadNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String areaName
        {
            get
            {
                return _areaName;
            }
            set
            {
                OnareaNameChanging(value);
                ReportPropertyChanging("areaName");
                _areaName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("areaName");
                OnareaNameChanged();
            }
        }
        private global::System.String _areaName;
        partial void OnareaNameChanging(global::System.String value);
        partial void OnareaNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> doorPost
        {
            get
            {
                return _doorPost;
            }
            set
            {
                OndoorPostChanging(value);
                ReportPropertyChanging("doorPost");
                _doorPost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("doorPost");
                OndoorPostChanged();
            }
        }
        private Nullable<global::System.Int32> _doorPost;
        partial void OndoorPostChanging(Nullable<global::System.Int32> value);
        partial void OndoorPostChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String zip
        {
            get
            {
                return _zip;
            }
            set
            {
                OnzipChanging(value);
                ReportPropertyChanging("zip");
                _zip = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("zip");
                OnzipChanged();
            }
        }
        private global::System.String _zip;
        partial void OnzipChanging(global::System.String value);
        partial void OnzipChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tel
        {
            get
            {
                return _tel;
            }
            set
            {
                OntelChanging(value);
                ReportPropertyChanging("tel");
                _tel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tel");
                OntelChanged();
            }
        }
        private global::System.String _tel;
        partial void OntelChanging(global::System.String value);
        partial void OntelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tel1
        {
            get
            {
                return _tel1;
            }
            set
            {
                Ontel1Changing(value);
                ReportPropertyChanging("tel1");
                _tel1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tel1");
                Ontel1Changed();
            }
        }
        private global::System.String _tel1;
        partial void Ontel1Changing(global::System.String value);
        partial void Ontel1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tel2
        {
            get
            {
                return _tel2;
            }
            set
            {
                Ontel2Changing(value);
                ReportPropertyChanging("tel2");
                _tel2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tel2");
                Ontel2Changed();
            }
        }
        private global::System.String _tel2;
        partial void Ontel2Changing(global::System.String value);
        partial void Ontel2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String busiCircles
        {
            get
            {
                return _busiCircles;
            }
            set
            {
                OnbusiCirclesChanging(value);
                ReportPropertyChanging("busiCircles");
                _busiCircles = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("busiCircles");
                OnbusiCirclesChanged();
            }
        }
        private global::System.String _busiCircles;
        partial void OnbusiCirclesChanging(global::System.String value);
        partial void OnbusiCirclesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String courtyard
        {
            get
            {
                return _courtyard;
            }
            set
            {
                OncourtyardChanging(value);
                ReportPropertyChanging("courtyard");
                _courtyard = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("courtyard");
                OncourtyardChanged();
            }
        }
        private global::System.String _courtyard;
        partial void OncourtyardChanging(global::System.String value);
        partial void OncourtyardChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> addrType
        {
            get
            {
                return _addrType;
            }
            set
            {
                OnaddrTypeChanging(value);
                ReportPropertyChanging("addrType");
                _addrType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("addrType");
                OnaddrTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _addrType;
        partial void OnaddrTypeChanging(Nullable<global::System.Int32> value);
        partial void OnaddrTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String definedZip
        {
            get
            {
                return _definedZip;
            }
            set
            {
                OndefinedZipChanging(value);
                ReportPropertyChanging("definedZip");
                _definedZip = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definedZip");
                OndefinedZipChanged();
            }
        }
        private global::System.String _definedZip;
        partial void OndefinedZipChanging(global::System.String value);
        partial void OndefinedZipChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String memo
        {
            get
            {
                return _memo;
            }
            set
            {
                OnmemoChanging(value);
                ReportPropertyChanging("memo");
                _memo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("memo");
                OnmemoChanged();
            }
        }
        private global::System.String _memo;
        partial void OnmemoChanging(global::System.String value);
        partial void OnmemoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> beSendAddr
        {
            get
            {
                return _beSendAddr;
            }
            set
            {
                OnbeSendAddrChanging(value);
                ReportPropertyChanging("beSendAddr");
                _beSendAddr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("beSendAddr");
                OnbeSendAddrChanged();
            }
        }
        private Nullable<global::System.Int32> _beSendAddr;
        partial void OnbeSendAddrChanging(Nullable<global::System.Int32> value);
        partial void OnbeSendAddrChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime createTime
        {
            get
            {
                return _createTime;
            }
            set
            {
                OncreateTimeChanging(value);
                ReportPropertyChanging("createTime");
                _createTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createTime");
                OncreateTimeChanged();
            }
        }
        private global::System.DateTime _createTime;
        partial void OncreateTimeChanging(global::System.DateTime value);
        partial void OncreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String createBy
        {
            get
            {
                return _createBy;
            }
            set
            {
                OncreateByChanging(value);
                ReportPropertyChanging("createBy");
                _createBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("createBy");
                OncreateByChanged();
            }
        }
        private global::System.String _createBy;
        partial void OncreateByChanging(global::System.String value);
        partial void OncreateByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> updateTime
        {
            get
            {
                return _updateTime;
            }
            set
            {
                OnupdateTimeChanging(value);
                ReportPropertyChanging("updateTime");
                _updateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("updateTime");
                OnupdateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _updateTime;
        partial void OnupdateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnupdateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String updateBy
        {
            get
            {
                return _updateBy;
            }
            set
            {
                OnupdateByChanging(value);
                ReportPropertyChanging("updateBy");
                _updateBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("updateBy");
                OnupdateByChanged();
            }
        }
        private global::System.String _updateBy;
        partial void OnupdateByChanging(global::System.String value);
        partial void OnupdateByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> regionId
        {
            get
            {
                return _regionId;
            }
            set
            {
                OnregionIdChanging(value);
                ReportPropertyChanging("regionId");
                _regionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("regionId");
                OnregionIdChanged();
            }
        }
        private Nullable<global::System.Int32> _regionId;
        partial void OnregionIdChanging(Nullable<global::System.Int32> value);
        partial void OnregionIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nearRoad
        {
            get
            {
                return _nearRoad;
            }
            set
            {
                OnnearRoadChanging(value);
                ReportPropertyChanging("nearRoad");
                _nearRoad = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nearRoad");
                OnnearRoadChanged();
            }
        }
        private global::System.String _nearRoad;
        partial void OnnearRoadChanging(global::System.String value);
        partial void OnnearRoadChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> provinceId
        {
            get
            {
                return _provinceId;
            }
            set
            {
                OnprovinceIdChanging(value);
                ReportPropertyChanging("provinceId");
                _provinceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("provinceId");
                OnprovinceIdChanged();
            }
        }
        private Nullable<global::System.Int32> _provinceId;
        partial void OnprovinceIdChanging(Nullable<global::System.Int32> value);
        partial void OnprovinceIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> districtId
        {
            get
            {
                return _districtId;
            }
            set
            {
                OndistrictIdChanging(value);
                ReportPropertyChanging("districtId");
                _districtId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("districtId");
                OndistrictIdChanged();
            }
        }
        private Nullable<global::System.Int32> _districtId;
        partial void OndistrictIdChanging(Nullable<global::System.Int32> value);
        partial void OndistrictIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EF.Model.bbHomeModel", Name="base_t_member")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class base_t_member : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 base_t_member 对象。
        /// </summary>
        /// <param name="membNo">membNo 属性的初始值。</param>
        /// <param name="orderTimes">orderTimes 属性的初始值。</param>
        public static base_t_member Createbase_t_member(global::System.Int32 membNo, global::System.Int32 orderTimes)
        {
            base_t_member base_t_member = new base_t_member();
            base_t_member.membNo = membNo;
            base_t_member.orderTimes = orderTimes;
            return base_t_member;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 membNo
        {
            get
            {
                return _membNo;
            }
            set
            {
                if (_membNo != value)
                {
                    OnmembNoChanging(value);
                    ReportPropertyChanging("membNo");
                    _membNo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("membNo");
                    OnmembNoChanged();
                }
            }
        }
        private global::System.Int32 _membNo;
        partial void OnmembNoChanging(global::System.Int32 value);
        partial void OnmembNoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String userCode
        {
            get
            {
                return _userCode;
            }
            set
            {
                OnuserCodeChanging(value);
                ReportPropertyChanging("userCode");
                _userCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("userCode");
                OnuserCodeChanged();
            }
        }
        private global::System.String _userCode;
        partial void OnuserCodeChanging(global::System.String value);
        partial void OnuserCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String userName
        {
            get
            {
                return _userName;
            }
            set
            {
                OnuserNameChanging(value);
                ReportPropertyChanging("userName");
                _userName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("userName");
                OnuserNameChanged();
            }
        }
        private global::System.String _userName;
        partial void OnuserNameChanging(global::System.String value);
        partial void OnuserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> regTime
        {
            get
            {
                return _regTime;
            }
            set
            {
                OnregTimeChanging(value);
                ReportPropertyChanging("regTime");
                _regTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("regTime");
                OnregTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _regTime;
        partial void OnregTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnregTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String createBy
        {
            get
            {
                return _createBy;
            }
            set
            {
                OncreateByChanging(value);
                ReportPropertyChanging("createBy");
                _createBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("createBy");
                OncreateByChanged();
            }
        }
        private global::System.String _createBy;
        partial void OncreateByChanging(global::System.String value);
        partial void OncreateByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> updateTime
        {
            get
            {
                return _updateTime;
            }
            set
            {
                OnupdateTimeChanging(value);
                ReportPropertyChanging("updateTime");
                _updateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("updateTime");
                OnupdateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _updateTime;
        partial void OnupdateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnupdateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String updateBy
        {
            get
            {
                return _updateBy;
            }
            set
            {
                OnupdateByChanging(value);
                ReportPropertyChanging("updateBy");
                _updateBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("updateBy");
                OnupdateByChanged();
            }
        }
        private global::System.String _updateBy;
        partial void OnupdateByChanging(global::System.String value);
        partial void OnupdateByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cardNO
        {
            get
            {
                return _cardNO;
            }
            set
            {
                OncardNOChanging(value);
                ReportPropertyChanging("cardNO");
                _cardNO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cardNO");
                OncardNOChanged();
            }
        }
        private global::System.String _cardNO;
        partial void OncardNOChanging(global::System.String value);
        partial void OncardNOChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> noteFlag
        {
            get
            {
                return _noteFlag;
            }
            set
            {
                OnnoteFlagChanging(value);
                ReportPropertyChanging("noteFlag");
                _noteFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("noteFlag");
                OnnoteFlagChanged();
            }
        }
        private Nullable<global::System.Int32> _noteFlag;
        partial void OnnoteFlagChanging(Nullable<global::System.Int32> value);
        partial void OnnoteFlagChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> userGroupId
        {
            get
            {
                return _userGroupId;
            }
            set
            {
                OnuserGroupIdChanging(value);
                ReportPropertyChanging("userGroupId");
                _userGroupId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userGroupId");
                OnuserGroupIdChanged();
            }
        }
        private Nullable<global::System.Int32> _userGroupId;
        partial void OnuserGroupIdChanging(Nullable<global::System.Int32> value);
        partial void OnuserGroupIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> policymaker
        {
            get
            {
                return _policymaker;
            }
            set
            {
                OnpolicymakerChanging(value);
                ReportPropertyChanging("policymaker");
                _policymaker = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("policymaker");
                OnpolicymakerChanged();
            }
        }
        private Nullable<global::System.Int32> _policymaker;
        partial void OnpolicymakerChanging(Nullable<global::System.Int32> value);
        partial void OnpolicymakerChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ReferrerMembNo
        {
            get
            {
                return _ReferrerMembNo;
            }
            set
            {
                OnReferrerMembNoChanging(value);
                ReportPropertyChanging("ReferrerMembNo");
                _ReferrerMembNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReferrerMembNo");
                OnReferrerMembNoChanged();
            }
        }
        private Nullable<global::System.Int32> _ReferrerMembNo;
        partial void OnReferrerMembNoChanging(Nullable<global::System.Int32> value);
        partial void OnReferrerMembNoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> province
        {
            get
            {
                return _province;
            }
            set
            {
                OnprovinceChanging(value);
                ReportPropertyChanging("province");
                _province = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("province");
                OnprovinceChanged();
            }
        }
        private Nullable<global::System.Int32> _province;
        partial void OnprovinceChanging(Nullable<global::System.Int32> value);
        partial void OnprovinceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> city
        {
            get
            {
                return _city;
            }
            set
            {
                OncityChanging(value);
                ReportPropertyChanging("city");
                _city = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("city");
                OncityChanged();
            }
        }
        private Nullable<global::System.Int32> _city;
        partial void OncityChanging(Nullable<global::System.Int32> value);
        partial void OncityChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> district
        {
            get
            {
                return _district;
            }
            set
            {
                OndistrictChanging(value);
                ReportPropertyChanging("district");
                _district = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("district");
                OndistrictChanged();
            }
        }
        private Nullable<global::System.Int32> _district;
        partial void OndistrictChanging(Nullable<global::System.Int32> value);
        partial void OndistrictChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> scores
        {
            get
            {
                return _scores;
            }
            set
            {
                OnscoresChanging(value);
                ReportPropertyChanging("scores");
                _scores = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("scores");
                OnscoresChanged();
            }
        }
        private Nullable<global::System.Int32> _scores;
        partial void OnscoresChanging(Nullable<global::System.Int32> value);
        partial void OnscoresChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> valid
        {
            get
            {
                return _valid;
            }
            set
            {
                OnvalidChanging(value);
                ReportPropertyChanging("valid");
                _valid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("valid");
                OnvalidChanged();
            }
        }
        private Nullable<global::System.Int32> _valid;
        partial void OnvalidChanging(Nullable<global::System.Int32> value);
        partial void OnvalidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mobileTel
        {
            get
            {
                return _mobileTel;
            }
            set
            {
                OnmobileTelChanging(value);
                ReportPropertyChanging("mobileTel");
                _mobileTel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mobileTel");
                OnmobileTelChanged();
            }
        }
        private global::System.String _mobileTel;
        partial void OnmobileTelChanging(global::System.String value);
        partial void OnmobileTelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tel
        {
            get
            {
                return _tel;
            }
            set
            {
                OntelChanging(value);
                ReportPropertyChanging("tel");
                _tel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tel");
                OntelChanged();
            }
        }
        private global::System.String _tel;
        partial void OntelChanging(global::System.String value);
        partial void OntelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> userLevel
        {
            get
            {
                return _userLevel;
            }
            set
            {
                OnuserLevelChanging(value);
                ReportPropertyChanging("userLevel");
                _userLevel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userLevel");
                OnuserLevelChanged();
            }
        }
        private Nullable<global::System.Int32> _userLevel;
        partial void OnuserLevelChanging(Nullable<global::System.Int32> value);
        partial void OnuserLevelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> areaNo
        {
            get
            {
                return _areaNo;
            }
            set
            {
                OnareaNoChanging(value);
                ReportPropertyChanging("areaNo");
                _areaNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("areaNo");
                OnareaNoChanged();
            }
        }
        private Nullable<global::System.Int32> _areaNo;
        partial void OnareaNoChanging(Nullable<global::System.Int32> value);
        partial void OnareaNoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> regType
        {
            get
            {
                return _regType;
            }
            set
            {
                OnregTypeChanging(value);
                ReportPropertyChanging("regType");
                _regType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("regType");
                OnregTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _regType;
        partial void OnregTypeChanging(Nullable<global::System.Int32> value);
        partial void OnregTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> clusterId
        {
            get
            {
                return _clusterId;
            }
            set
            {
                OnclusterIdChanging(value);
                ReportPropertyChanging("clusterId");
                _clusterId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("clusterId");
                OnclusterIdChanged();
            }
        }
        private Nullable<global::System.Int32> _clusterId;
        partial void OnclusterIdChanging(Nullable<global::System.Int32> value);
        partial void OnclusterIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> regFrom
        {
            get
            {
                return _regFrom;
            }
            set
            {
                OnregFromChanging(value);
                ReportPropertyChanging("regFrom");
                _regFrom = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("regFrom");
                OnregFromChanged();
            }
        }
        private Nullable<global::System.Int32> _regFrom;
        partial void OnregFromChanging(Nullable<global::System.Int32> value);
        partial void OnregFromChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String passward
        {
            get
            {
                return _passward;
            }
            set
            {
                OnpasswardChanging(value);
                ReportPropertyChanging("passward");
                _passward = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("passward");
                OnpasswardChanged();
            }
        }
        private global::System.String _passward;
        partial void OnpasswardChanging(global::System.String value);
        partial void OnpasswardChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nickName
        {
            get
            {
                return _nickName;
            }
            set
            {
                OnnickNameChanging(value);
                ReportPropertyChanging("nickName");
                _nickName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nickName");
                OnnickNameChanged();
            }
        }
        private global::System.String _nickName;
        partial void OnnickNameChanging(global::System.String value);
        partial void OnnickNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> sex
        {
            get
            {
                return _sex;
            }
            set
            {
                OnsexChanging(value);
                ReportPropertyChanging("sex");
                _sex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sex");
                OnsexChanged();
            }
        }
        private Nullable<global::System.Byte> _sex;
        partial void OnsexChanging(Nullable<global::System.Byte> value);
        partial void OnsexChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String question
        {
            get
            {
                return _question;
            }
            set
            {
                OnquestionChanging(value);
                ReportPropertyChanging("question");
                _question = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("question");
                OnquestionChanged();
            }
        }
        private global::System.String _question;
        partial void OnquestionChanging(global::System.String value);
        partial void OnquestionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String answer
        {
            get
            {
                return _answer;
            }
            set
            {
                OnanswerChanging(value);
                ReportPropertyChanging("answer");
                _answer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("answer");
                OnanswerChanged();
            }
        }
        private global::System.String _answer;
        partial void OnanswerChanging(global::System.String value);
        partial void OnanswerChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String qq
        {
            get
            {
                return _qq;
            }
            set
            {
                OnqqChanging(value);
                ReportPropertyChanging("qq");
                _qq = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("qq");
                OnqqChanged();
            }
        }
        private global::System.String _qq;
        partial void OnqqChanging(global::System.String value);
        partial void OnqqChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String msn
        {
            get
            {
                return _msn;
            }
            set
            {
                OnmsnChanging(value);
                ReportPropertyChanging("msn");
                _msn = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("msn");
                OnmsnChanged();
            }
        }
        private global::System.String _msn;
        partial void OnmsnChanging(global::System.String value);
        partial void OnmsnChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> beValidate
        {
            get
            {
                return _beValidate;
            }
            set
            {
                OnbeValidateChanging(value);
                ReportPropertyChanging("beValidate");
                _beValidate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("beValidate");
                OnbeValidateChanged();
            }
        }
        private Nullable<global::System.Int32> _beValidate;
        partial void OnbeValidateChanging(Nullable<global::System.Int32> value);
        partial void OnbeValidateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 orderTimes
        {
            get
            {
                return _orderTimes;
            }
            set
            {
                OnorderTimesChanging(value);
                ReportPropertyChanging("orderTimes");
                _orderTimes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("orderTimes");
                OnorderTimesChanged();
            }
        }
        private global::System.Int32 _orderTimes;
        partial void OnorderTimesChanging(global::System.Int32 value);
        partial void OnorderTimesChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EF.Model.bbHomeModel", Name="system_log")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class system_log : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 system_log 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="date">Date 属性的初始值。</param>
        /// <param name="thread">Thread 属性的初始值。</param>
        /// <param name="level">Level 属性的初始值。</param>
        /// <param name="logger">Logger 属性的初始值。</param>
        /// <param name="message">Message 属性的初始值。</param>
        public static system_log Createsystem_log(global::System.Int32 id, global::System.DateTime date, global::System.String thread, global::System.String level, global::System.String logger, global::System.String message)
        {
            system_log system_log = new system_log();
            system_log.Id = id;
            system_log.Date = date;
            system_log.Thread = thread;
            system_log.Level = level;
            system_log.Logger = logger;
            system_log.Message = message;
            return system_log;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                if (_Date != value)
                {
                    OnDateChanging(value);
                    ReportPropertyChanging("Date");
                    _Date = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Date");
                    OnDateChanged();
                }
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Thread
        {
            get
            {
                return _Thread;
            }
            set
            {
                if (_Thread != value)
                {
                    OnThreadChanging(value);
                    ReportPropertyChanging("Thread");
                    _Thread = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Thread");
                    OnThreadChanged();
                }
            }
        }
        private global::System.String _Thread;
        partial void OnThreadChanging(global::System.String value);
        partial void OnThreadChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Level
        {
            get
            {
                return _Level;
            }
            set
            {
                if (_Level != value)
                {
                    OnLevelChanging(value);
                    ReportPropertyChanging("Level");
                    _Level = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Level");
                    OnLevelChanged();
                }
            }
        }
        private global::System.String _Level;
        partial void OnLevelChanging(global::System.String value);
        partial void OnLevelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Logger
        {
            get
            {
                return _Logger;
            }
            set
            {
                if (_Logger != value)
                {
                    OnLoggerChanging(value);
                    ReportPropertyChanging("Logger");
                    _Logger = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Logger");
                    OnLoggerChanged();
                }
            }
        }
        private global::System.String _Logger;
        partial void OnLoggerChanging(global::System.String value);
        partial void OnLoggerChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                if (_Message != value)
                {
                    OnMessageChanging(value);
                    ReportPropertyChanging("Message");
                    _Message = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Message");
                    OnMessageChanged();
                }
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Exception
        {
            get
            {
                return _Exception;
            }
            set
            {
                OnExceptionChanging(value);
                ReportPropertyChanging("Exception");
                _Exception = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Exception");
                OnExceptionChanged();
            }
        }
        private global::System.String _Exception;
        partial void OnExceptionChanging(global::System.String value);
        partial void OnExceptionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EF.Model.bbHomeModel", Name="System_Permission")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class System_Permission : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 System_Permission 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="created">Created 属性的初始值。</param>
        /// <param name="methodName">MethodName 属性的初始值。</param>
        /// <param name="isVerifySystemId">IsVerifySystemId 属性的初始值。</param>
        /// <param name="isVerifyToken">IsVerifyToken 属性的初始值。</param>
        /// <param name="isVerifyData">IsVerifyData 属性的初始值。</param>
        /// <param name="isVerfiyPemissions">IsVerfiyPemissions 属性的初始值。</param>
        /// <param name="className">ClassName 属性的初始值。</param>
        public static System_Permission CreateSystem_Permission(global::System.Int32 id, global::System.DateTime created, global::System.String methodName, global::System.Int16 isVerifySystemId, global::System.Int16 isVerifyToken, global::System.Int16 isVerifyData, global::System.Int16 isVerfiyPemissions, global::System.String className)
        {
            System_Permission system_Permission = new System_Permission();
            system_Permission.Id = id;
            system_Permission.Created = created;
            system_Permission.MethodName = methodName;
            system_Permission.IsVerifySystemId = isVerifySystemId;
            system_Permission.IsVerifyToken = isVerifyToken;
            system_Permission.IsVerifyData = isVerifyData;
            system_Permission.IsVerfiyPemissions = isVerfiyPemissions;
            system_Permission.ClassName = className;
            return system_Permission;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return _Created;
            }
            set
            {
                if (_Created != value)
                {
                    OnCreatedChanging(value);
                    ReportPropertyChanging("Created");
                    _Created = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Created");
                    OnCreatedChanged();
                }
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> RefreshTime
        {
            get
            {
                return _RefreshTime;
            }
            set
            {
                OnRefreshTimeChanging(value);
                ReportPropertyChanging("RefreshTime");
                _RefreshTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RefreshTime");
                OnRefreshTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _RefreshTime;
        partial void OnRefreshTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnRefreshTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MethodName
        {
            get
            {
                return _MethodName;
            }
            set
            {
                if (_MethodName != value)
                {
                    OnMethodNameChanging(value);
                    ReportPropertyChanging("MethodName");
                    _MethodName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MethodName");
                    OnMethodNameChanged();
                }
            }
        }
        private global::System.String _MethodName;
        partial void OnMethodNameChanging(global::System.String value);
        partial void OnMethodNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 IsVerifySystemId
        {
            get
            {
                return _IsVerifySystemId;
            }
            set
            {
                if (_IsVerifySystemId != value)
                {
                    OnIsVerifySystemIdChanging(value);
                    ReportPropertyChanging("IsVerifySystemId");
                    _IsVerifySystemId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IsVerifySystemId");
                    OnIsVerifySystemIdChanged();
                }
            }
        }
        private global::System.Int16 _IsVerifySystemId;
        partial void OnIsVerifySystemIdChanging(global::System.Int16 value);
        partial void OnIsVerifySystemIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 IsVerifyToken
        {
            get
            {
                return _IsVerifyToken;
            }
            set
            {
                if (_IsVerifyToken != value)
                {
                    OnIsVerifyTokenChanging(value);
                    ReportPropertyChanging("IsVerifyToken");
                    _IsVerifyToken = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IsVerifyToken");
                    OnIsVerifyTokenChanged();
                }
            }
        }
        private global::System.Int16 _IsVerifyToken;
        partial void OnIsVerifyTokenChanging(global::System.Int16 value);
        partial void OnIsVerifyTokenChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 IsVerifyData
        {
            get
            {
                return _IsVerifyData;
            }
            set
            {
                if (_IsVerifyData != value)
                {
                    OnIsVerifyDataChanging(value);
                    ReportPropertyChanging("IsVerifyData");
                    _IsVerifyData = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IsVerifyData");
                    OnIsVerifyDataChanged();
                }
            }
        }
        private global::System.Int16 _IsVerifyData;
        partial void OnIsVerifyDataChanging(global::System.Int16 value);
        partial void OnIsVerifyDataChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 IsVerfiyPemissions
        {
            get
            {
                return _IsVerfiyPemissions;
            }
            set
            {
                if (_IsVerfiyPemissions != value)
                {
                    OnIsVerfiyPemissionsChanging(value);
                    ReportPropertyChanging("IsVerfiyPemissions");
                    _IsVerfiyPemissions = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IsVerfiyPemissions");
                    OnIsVerfiyPemissionsChanged();
                }
            }
        }
        private global::System.Int16 _IsVerfiyPemissions;
        partial void OnIsVerfiyPemissionsChanging(global::System.Int16 value);
        partial void OnIsVerfiyPemissionsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AssemblyName
        {
            get
            {
                return _AssemblyName;
            }
            set
            {
                OnAssemblyNameChanging(value);
                ReportPropertyChanging("AssemblyName");
                _AssemblyName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AssemblyName");
                OnAssemblyNameChanged();
            }
        }
        private global::System.String _AssemblyName;
        partial void OnAssemblyNameChanging(global::System.String value);
        partial void OnAssemblyNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClassName
        {
            get
            {
                return _ClassName;
            }
            set
            {
                if (_ClassName != value)
                {
                    OnClassNameChanging(value);
                    ReportPropertyChanging("ClassName");
                    _ClassName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ClassName");
                    OnClassNameChanged();
                }
            }
        }
        private global::System.String _ClassName;
        partial void OnClassNameChanging(global::System.String value);
        partial void OnClassNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AfferentParameters
        {
            get
            {
                return _AfferentParameters;
            }
            set
            {
                OnAfferentParametersChanging(value);
                ReportPropertyChanging("AfferentParameters");
                _AfferentParameters = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AfferentParameters");
                OnAfferentParametersChanged();
            }
        }
        private global::System.String _AfferentParameters;
        partial void OnAfferentParametersChanging(global::System.String value);
        partial void OnAfferentParametersChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReturnParameters
        {
            get
            {
                return _ReturnParameters;
            }
            set
            {
                OnReturnParametersChanging(value);
                ReportPropertyChanging("ReturnParameters");
                _ReturnParameters = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReturnParameters");
                OnReturnParametersChanged();
            }
        }
        private global::System.String _ReturnParameters;
        partial void OnReturnParametersChanging(global::System.String value);
        partial void OnReturnParametersChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EF.Model.bbHomeModel", Name="tb_Blacklist")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_Blacklist : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tb_Blacklist 对象。
        /// </summary>
        /// <param name="intBlackID">intBlackID 属性的初始值。</param>
        /// <param name="intUserID">intUserID 属性的初始值。</param>
        public static tb_Blacklist Createtb_Blacklist(global::System.Int32 intBlackID, global::System.Int32 intUserID)
        {
            tb_Blacklist tb_Blacklist = new tb_Blacklist();
            tb_Blacklist.intBlackID = intBlackID;
            tb_Blacklist.intUserID = intUserID;
            return tb_Blacklist;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 intBlackID
        {
            get
            {
                return _intBlackID;
            }
            set
            {
                if (_intBlackID != value)
                {
                    OnintBlackIDChanging(value);
                    ReportPropertyChanging("intBlackID");
                    _intBlackID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("intBlackID");
                    OnintBlackIDChanged();
                }
            }
        }
        private global::System.Int32 _intBlackID;
        partial void OnintBlackIDChanging(global::System.Int32 value);
        partial void OnintBlackIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 intUserID
        {
            get
            {
                return _intUserID;
            }
            set
            {
                OnintUserIDChanging(value);
                ReportPropertyChanging("intUserID");
                _intUserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("intUserID");
                OnintUserIDChanged();
            }
        }
        private global::System.Int32 _intUserID;
        partial void OnintUserIDChanging(global::System.Int32 value);
        partial void OnintUserIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vchUserName
        {
            get
            {
                return _vchUserName;
            }
            set
            {
                OnvchUserNameChanging(value);
                ReportPropertyChanging("vchUserName");
                _vchUserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vchUserName");
                OnvchUserNameChanged();
            }
        }
        private global::System.String _vchUserName;
        partial void OnvchUserNameChanging(global::System.String value);
        partial void OnvchUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vchTel
        {
            get
            {
                return _vchTel;
            }
            set
            {
                OnvchTelChanging(value);
                ReportPropertyChanging("vchTel");
                _vchTel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vchTel");
                OnvchTelChanged();
            }
        }
        private global::System.String _vchTel;
        partial void OnvchTelChanging(global::System.String value);
        partial void OnvchTelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vchMobile
        {
            get
            {
                return _vchMobile;
            }
            set
            {
                OnvchMobileChanging(value);
                ReportPropertyChanging("vchMobile");
                _vchMobile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vchMobile");
                OnvchMobileChanged();
            }
        }
        private global::System.String _vchMobile;
        partial void OnvchMobileChanging(global::System.String value);
        partial void OnvchMobileChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vchAddress
        {
            get
            {
                return _vchAddress;
            }
            set
            {
                OnvchAddressChanging(value);
                ReportPropertyChanging("vchAddress");
                _vchAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vchAddress");
                OnvchAddressChanged();
            }
        }
        private global::System.String _vchAddress;
        partial void OnvchAddressChanging(global::System.String value);
        partial void OnvchAddressChanged();

        #endregion
    
    }

    #endregion
    
}
